/** @type {import('tailwindcss').Config} */

function withOpacity(variable) {
  return ({ opacityValue }) => {
    if (opacityValue === undefined) return `rgb(var(${variable}))`;
    return `rgb(var(${variable}) / ${opacityValue})`;
  };
}

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f3f0ec",
        "on-primary-fixed-variant": "#5f402c",
        "secondary-fixed-dim": "#4ae183",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#862117",
        "surface-container-high": withOpacity("--color-surface-container-high"),
        "tertiary-container": "#6c0d07",
        "surface-bright": "#fcf9f5",
        "secondary-fixed": "#6bfe9c",
        "outline-variant": "#d4c3bb",
        background: withOpacity("--color-background"),
        "on-tertiary-container": "#f87563",
        "inverse-surface": "#31302e",
        "surface-container-low": withOpacity("--color-surface-container-low"),
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#00743a",
        "surface-tint": "#795741",
        tertiary: "#480000",
        outline: "#82746d",
        "surface-dim": "#dcdad6",
        "on-background": "#1c1c1a",
        "surface-container": withOpacity("--color-surface-container"),
        primary: withOpacity("--color-primary"),
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbc7",
        "on-secondary-fixed": "#00210c",
        "on-surface": withOpacity("--color-on-surface"),
        "on-surface-variant": withOpacity("--color-on-surface-variant"),
        secondary: "#006d37",
        "primary-container": "#4a2e1b",
        "on-primary-container": "#bd957c",
        "on-secondary-fixed-variant": "#005228",
        "on-primary": "#ffffff",
        "inverse-primary": "#eabda3",
        surface: withOpacity("--color-surface"),
        "surface-container-highest": withOpacity("--color-surface-container-highest"),
        "primary-fixed-dim": "#eabda3",
        "error-container": "#ffdad6",
        "surface-container-lowest": withOpacity("--color-surface-container-lowest"),
        "on-primary-fixed": "#2d1605",
        "on-tertiary-fixed": "#410000",
        "surface-variant": "#e5e2de",
        "tertiary-fixed": "#ffdad4",
        "secondary-container": "#6bfe9c",
        "tertiary-fixed-dim": "#ffb4a8",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        margin: "1rem",
        "gutter-desktop": "1.75rem",
        "margin-tablet": "2rem",
        gutter: "1.25rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Quicksand", "sans-serif"],
        "headline-sm": ["Quicksand", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Quicksand", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};